# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatserver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='cuser',
        ),
        migrations.AlterField(
            model_name='chatserver',
            name='cuser',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='chat',
        ),
    ]
