# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 01:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20180627_2253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatServer',
            new_name='chat',
        ),
    ]
