# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 02:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20180628_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='cuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
