# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_profile_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('body', models.CharField(max_length=200)),
            ],
        ),
    ]
