# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180622_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.FileField(blank=True, upload_to='pic_folder/'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo1',
            field=models.FileField(blank=True, upload_to='pic_folder/'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo2',
            field=models.FileField(blank=True, upload_to='pic_folder/'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo3',
            field=models.FileField(blank=True, upload_to='pic_folder/'),
        ),
    ]
