# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20180726_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='besttravel',
            new_name='bestseason',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='condition',
            new_name='experiencerequired',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='hotel',
            new_name='hotels',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='major',
            new_name='majorattraction',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='attitude',
            new_name='maxattitude',
        ),
    ]
