# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20180622_2001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adds',
            new_name='Add',
        ),
        migrations.RenameField(
            model_name='add',
            old_name='place',
            new_name='plc',
        ),
    ]
